import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_CENTER

PAGE_W = A4[0] - 36 * mm

CYAN    = colors.HexColor("#06b6d4")
SLATE   = colors.HexColor("#334155")
LIGHT   = colors.HexColor("#f1f5f9")
WHITE   = colors.white
AMBER   = colors.HexColor("#f59e0b")
EMERALD = colors.HexColor("#10b981")
ROSE    = colors.HexColor("#f43f5e")
VIOLET  = colors.HexColor("#8b5cf6")
DARK    = colors.HexColor("#0f172a")
ORANGE  = colors.HexColor("#f97316")


def _styles():
    return {
        "title":    ParagraphStyle("title",    fontSize=22, textColor=DARK,  leading=28, spaceAfter=0, fontName="Helvetica-Bold"),
        "subtitle": ParagraphStyle("subtitle", fontSize=11, textColor=SLATE, leading=14, spaceAfter=0, fontName="Helvetica"),
        "section":  ParagraphStyle("section",  fontSize=13, textColor=DARK,  spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold"),
        "body":     ParagraphStyle("body",     fontSize=10, textColor=SLATE, leading=15, spaceAfter=4, fontName="Helvetica"),
        "label":    ParagraphStyle("label",    fontSize=8,  textColor=colors.HexColor("#94a3b8"), fontName="Helvetica-Bold", spaceAfter=2),
        "small":    ParagraphStyle("small",    fontSize=8,  textColor=SLATE, leading=11, fontName="Helvetica"),
    }


def _header(story, S, title, subtitle, filename):
    t = Table(
        [
            [Paragraph(title, S["title"])],
            [Paragraph(subtitle, S["subtitle"])],
            [Paragraph(f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M')}", S["subtitle"])],
        ],
        colWidths=[PAGE_W], rowHeights=[36, 18, 18],
    )
    t.setStyle(TableStyle([
        ("TOPPADDING",    (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("LEFTPADDING",   (0, 0), (-1, -1), 0),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 0),
        ("VALIGN",        (0, 0), (-1, -1), "BOTTOM"),
    ]))
    story.append(t)
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=1, color=CYAN, spaceAfter=10))


def _footer(story):
    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0")))
    story.append(Paragraph(
        "Generated by <b>AI Insights Tool</b> — sohilnagpal.com",
        ParagraphStyle("footer", fontSize=8, textColor=colors.HexColor("#94a3b8"),
                       alignment=TA_CENTER, spaceBefore=4)
    ))


def _kpi_row(stats):
    """Cyan-header stat chips: [(label, value), ...]"""
    data  = [[v for _, v in stats], [l for l, _ in stats]]
    col_w = PAGE_W / len(stats)
    t = Table(data, colWidths=[col_w] * len(stats))
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), CYAN),
        ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 15),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS",(0, 1), (-1, 1), [LIGHT]),
        ("TEXTCOLOR",     (0, 1), (-1, 1), SLATE),
        ("FONTSIZE",      (0, 1), (-1, 1), 8),
        ("FONTNAME",      (0, 1), (-1, 1), "Helvetica"),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("GRID",          (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
    ]))
    return t


def _fmt_money(n):
    if n is None: return "—"
    try:
        n = float(n)
        if n >= 1e6: return f"${n/1e6:.1f}M"
        if n >= 1e3: return f"${n/1e3:.0f}K"
        return f"${n:.0f}"
    except Exception:
        return str(n)


def _section(story, S, title, color=None):
    story.append(Paragraph(title, S["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=color or SLATE, spaceAfter=6))


def _highlight_box(text, bg, border, S):
    t = Table(
        [[Paragraph(text, ParagraphStyle("hb", fontSize=10, textColor=DARK, leading=15, fontName="Helvetica"))]],
        colWidths=[PAGE_W],
    )
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), bg),
        ("BOX",           (0, 0), (-1, -1), 1.5, border),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING",   (0, 0), (-1, -1), 10),
    ]))
    return t


# ── HubSpot Deals PDF ─────────────────────────────────────────────────────────

def _pdf_deals(story, S, hs):
    _section(story, S, "Pipeline Summary", CYAN)
    story.append(_kpi_row([
        ("Total Pipeline",  _fmt_money(hs.get("total_pipeline"))),
        ("Weighted Value",  _fmt_money(hs.get("weighted_pipeline"))),
        ("Avg Deal Size",   _fmt_money(hs.get("avg_deal_size"))),
        ("Win Rate",        f"{hs.get('win_rate', 0)}%"),
        ("Open Deals",      str(hs.get("open_deals", 0))),
    ]))
    story.append(Spacer(1, 10))

    # Won / Lost
    won  = hs.get("won_deals", 0)
    lost = hs.get("lost_deals", 0)
    wl = Table(
        [["Closed Won", "Closed Lost"], [str(won), str(lost)]],
        colWidths=[PAGE_W / 2, PAGE_W / 2],
    )
    wl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (0, 0), EMERALD),
        ("BACKGROUND",    (1, 0), (1, 0), ROSE),
        ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
        ("FONTNAME",      (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 9),
        ("FONTSIZE",      (0, 1), (-1, 1), 18),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS",(0, 1), (-1, 1), [colors.HexColor("#ecfdf5"), colors.HexColor("#fff1f2")]),
        ("TEXTCOLOR",     (0, 1), (0, 1), EMERALD),
        ("TEXTCOLOR",     (1, 1), (1, 1), ROSE),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("GRID",          (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
    ]))
    story.append(wl)
    story.append(Spacer(1, 10))

    # Pipeline by stage table
    pipeline = [s for s in (hs.get("pipeline_by_stage") or []) if s.get("stage") != "closedlost"]
    if pipeline:
        _section(story, S, "Pipeline by Stage", VIOLET)
        rows = [["Stage", "Deals", "Value"]] + [
            [s["label"], str(s["count"]), _fmt_money(s["value"])]
            for s in pipeline
        ]
        t = Table(rows, colWidths=[PAGE_W * 0.5, PAGE_W * 0.2, PAGE_W * 0.3])
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), DARK),
            ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("ALIGN",         (1, 0), (-1, -1), "RIGHT"),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, LIGHT]),
            ("TEXTCOLOR",     (0, 1), (-1, -1), SLATE),
            ("GRID",          (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t)
        story.append(Spacer(1, 10))

    # At-risk deals
    at_risk = hs.get("at_risk_deals") or []
    if at_risk:
        _section(story, S, "Deals Needing Attention", AMBER)
        rows = [["Deal Name", "Stage", "Value", "Risk"]] + [
            [
                Paragraph(d.get("name", "—"), S["small"]),
                d.get("stage", "—"),
                _fmt_money(d.get("amount")),
                f"{d['days_overdue']}d overdue" if d.get("days_overdue") is not None else "No close date",
            ]
            for d in at_risk
        ]
        cw = [PAGE_W * 0.38, PAGE_W * 0.22, PAGE_W * 0.18, PAGE_W * 0.22]
        t = Table(rows, colWidths=cw)
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), AMBER),
            ("TEXTCOLOR",     (0, 0), (-1, 0), DARK),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",      (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, colors.HexColor("#fffbeb")]),
            ("TEXTCOLOR",     (0, 1), (-1, -1), SLATE),
            ("GRID",          (0, 0), (-1, -1), 0.4, colors.HexColor("#fde68a")),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(t)


# ── HubSpot Contacts PDF ──────────────────────────────────────────────────────

def _pdf_contacts(story, S, hs):
    _section(story, S, "Contact Summary", CYAN)
    story.append(_kpi_row([
        ("Total Contacts", str(hs.get("total_contacts", 0))),
        ("MQLs",           str(hs.get("mqls", 0))),
        ("SQLs",           str(hs.get("sqls", 0))),
        ("Customers",      str(hs.get("customers", 0))),
        ("Conv. Rate",     f"{hs.get('conversion_rate', 0)}%"),
    ]))
    story.append(Spacer(1, 10))

    # Lifecycle funnel
    funnel = [s for s in (hs.get("lifecycle_funnel") or []) if s.get("count", 0) > 0]
    if funnel:
        _section(story, S, "Lifecycle Funnel", VIOLET)
        rows = [["Stage", "Contacts", "% of Total"]]
        total = hs.get("total_contacts", 1) or 1
        for s in funnel:
            rows.append([s["label"], str(s["count"]), f"{s['count']/total*100:.1f}%"])
        t = Table(rows, colWidths=[PAGE_W * 0.5, PAGE_W * 0.25, PAGE_W * 0.25])
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), DARK),
            ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("ALIGN",         (1, 0), (-1, -1), "RIGHT"),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, LIGHT]),
            ("TEXTCOLOR",     (0, 1), (-1, -1), SLATE),
            ("GRID",          (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t)
        story.append(Spacer(1, 10))

    # Top countries
    countries = hs.get("top_countries") or {}
    if countries:
        _section(story, S, "Top Countries", CYAN)
        rows = [["Country", "Contacts"]] + [[k, str(v)] for k, v in list(countries.items())[:6]]
        t = Table(rows, colWidths=[PAGE_W * 0.7, PAGE_W * 0.3])
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), DARK),
            ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("ALIGN",         (1, 0), (-1, -1), "RIGHT"),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, LIGHT]),
            ("TEXTCOLOR",     (0, 1), (-1, -1), SLATE),
            ("GRID",          (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t)


# ── HubSpot Companies PDF ─────────────────────────────────────────────────────

def _pdf_companies(story, S, hs):
    _section(story, S, "Company Summary", CYAN)
    story.append(_kpi_row([
        ("Total Companies",    str(hs.get("total_companies", 0))),
        ("Avg Annual Revenue", _fmt_money(hs.get("avg_annual_revenue"))),
        ("Total Revenue",      _fmt_money(hs.get("total_revenue"))),
    ]))
    story.append(Spacer(1, 10))

    # Industry breakdown
    industries = hs.get("industries") or {}
    if industries:
        _section(story, S, "Industry Breakdown", VIOLET)
        rows = [["Industry", "Companies"]] + [
            [k.replace("_", " ").title(), str(v)] for k, v in list(industries.items())[:8]
        ]
        t = Table(rows, colWidths=[PAGE_W * 0.7, PAGE_W * 0.3])
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), DARK),
            ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("ALIGN",         (1, 0), (-1, -1), "RIGHT"),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, LIGHT]),
            ("TEXTCOLOR",     (0, 1), (-1, -1), SLATE),
            ("GRID",          (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t)
        story.append(Spacer(1, 10))

    # Size distribution
    sizes = hs.get("size_distribution") or {}
    if sizes:
        _section(story, S, "Company Size Distribution", CYAN)
        rows = [["Employees", "Companies"]] + [[k, str(v)] for k, v in sizes.items()]
        t = Table(rows, colWidths=[PAGE_W * 0.7, PAGE_W * 0.3])
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), DARK),
            ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("ALIGN",         (1, 0), (-1, -1), "RIGHT"),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, LIGHT]),
            ("TEXTCOLOR",     (0, 1), (-1, -1), SLATE),
            ("GRID",          (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t)


# ── Generic CSV sections ──────────────────────────────────────────────────────

def _pdf_generic(story, S, summary, insights):
    missing_total = sum(summary.get("missing_values", {}).values())
    story.append(_kpi_row([
        ("Rows",           str(summary.get("row_count", "—"))),
        ("Columns",        str(summary.get("column_count", "—"))),
        ("Anomalies",      str(summary.get("anomaly_count", 0))),
        ("Missing Values", str(missing_total)),
    ]))
    story.append(Spacer(1, 10))

    if insights:
        _section(story, S, "AI-Generated Insights")
        if insights.get("executive_summary"):
            story.append(Paragraph("Executive Summary", S["label"]))
            story.append(Paragraph(insights["executive_summary"], S["body"]))
            story.append(Spacer(1, 6))
        if insights.get("insights"):
            story.append(Paragraph("Key Insights", S["label"]))
            for ins in insights["insights"]:
                story.append(Paragraph(f"• <b>{ins['title']}</b>: {ins['detail']}", S["body"]))
            story.append(Spacer(1, 6))
        if insights.get("recommendation"):
            story.append(Paragraph("Recommendation", S["label"]))
            story.append(_highlight_box(insights["recommendation"], colors.HexColor("#ecfeff"), CYAN, S))
            story.append(Spacer(1, 6))
        if insights.get("anomalies"):
            story.append(Paragraph("Anomaly Analysis", S["label"]))
            story.append(_highlight_box(insights["anomalies"], colors.HexColor("#fffbeb"), AMBER, S))

    if summary.get("numeric_summary"):
        _section(story, S, "Numeric Summary")
        ns = summary["numeric_summary"]
        stats = ["mean", "std", "min", "50%", "max"]
        cols  = list((ns.get("mean") or {}).keys())
        if cols:
            header = ["Column"] + [s.upper() for s in stats]
            rows   = [header]
            for col in cols:
                row = [col]
                for s in stats:
                    v = (ns.get(s) or {}).get(col)
                    row.append(f"{v:.2f}" if v is not None else "—")
                rows.append(row)
            stat_col_w = (PAGE_W - 55 * mm) / len(stats)
            t = Table(rows, colWidths=[55 * mm] + [stat_col_w] * len(stats))
            t.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, 0), DARK),
                ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
                ("FONTNAME",      (0, 0), (-1, -1), "Helvetica"),
                ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE",      (0, 0), (-1, -1), 8),
                ("ALIGN",         (1, 0), (-1, -1), "RIGHT"),
                ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, LIGHT]),
                ("TEXTCOLOR",     (0, 1), (-1, -1), SLATE),
                ("GRID",          (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
                ("TOPPADDING",    (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]))
            story.append(t)

    if summary.get("top_correlations"):
        _section(story, S, "Top Correlations")
        corr_data = [["Column Pair", "Correlation"]] + [
            [c["columns"], f"{c['correlation']:.3f}"] for c in summary["top_correlations"]
        ]
        t = Table(corr_data, colWidths=[PAGE_W - 44 * mm, 44 * mm])
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), DARK),
            ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
            ("ALIGN",         (1, 0), (-1, -1), "CENTER"),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, LIGHT]),
            ("TEXTCOLOR",     (0, 1), (-1, -1), SLATE),
            ("GRID",          (0, 0), (-1, -1), 0.4, colors.HexColor("#e2e8f0")),
            ("TOPPADDING",    (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(t)

    anomaly_samples = summary.get("anomaly_sample", [])
    if anomaly_samples:
        _section(story, S, "Anomalous Row Samples", AMBER)
        story.append(Paragraph(
            f"{summary.get('anomaly_count', 0)} anomalous rows detected (showing first 5).",
            S["body"]
        ))
        cols = list(anomaly_samples[0].keys())
        col_w = PAGE_W / len(cols)
        hdr_s  = ParagraphStyle("ah", fontSize=7, textColor=DARK, fontName="Helvetica-Bold", leading=9)
        cell_s = ParagraphStyle("ac", fontSize=7, textColor=SLATE, fontName="Helvetica", leading=9)
        rows   = [[Paragraph(c, hdr_s) for c in cols]] + [
            [Paragraph(str(r.get(c, "—")), cell_s) for c in cols] for r in anomaly_samples
        ]
        t = Table(rows, colWidths=[col_w] * len(cols))
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), AMBER),
            ("FONTSIZE",      (0, 0), (-1, -1), 7),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, colors.HexColor("#fffbeb")]),
            ("GRID",          (0, 0), (-1, -1), 0.4, colors.HexColor("#fde68a")),
            ("TOPPADDING",    (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(t)


# ── Public entry point ────────────────────────────────────────────────────────

def generate_pdf(filename: str, summary: dict, insights: dict | None, hubspot: dict | None = None) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=18*mm, rightMargin=18*mm,
                            topMargin=18*mm, bottomMargin=18*mm)
    S     = _styles()
    story = []

    source = (hubspot or {}).get("source_type", "csv")

    # Title varies by source
    titles = {
        "hubspot_deals":     ("Sales Pipeline Report",    f"HubSpot Deals · {filename}"),
        "hubspot_contacts":  ("Contact Intelligence Report", f"HubSpot Contacts · {filename}"),
        "hubspot_companies": ("Company Intelligence Report",  f"HubSpot Companies · {filename}"),
    }
    title, subtitle = titles.get(source, ("AI Insights Report", f"Dataset: {filename}"))

    _header(story, S, title, subtitle, filename)

    if source == "hubspot_deals":
        _pdf_deals(story, S, hubspot)
    elif source == "hubspot_contacts":
        _pdf_contacts(story, S, hubspot)
    elif source == "hubspot_companies":
        _pdf_companies(story, S, hubspot)
    else:
        _pdf_generic(story, S, summary, insights)

    # Always append AI insights for HubSpot sources too
    if hubspot and insights:
        _section(story, S, "AI Analysis")
        if insights.get("executive_summary"):
            story.append(Paragraph(insights["executive_summary"], S["body"]))
            story.append(Spacer(1, 6))
        if insights.get("recommendation"):
            story.append(_highlight_box(insights["recommendation"], colors.HexColor("#ecfeff"), CYAN, S))

    _footer(story)
    doc.build(story)
    return buf.getvalue()
